### ISSUE TITLE
Not working in Atom 1.15.0

### ISSUE THREAD

**Issue by arshcaria** [naota/linter-spell-cjk#1]
I installed the plugin but CJK characters are sill underlined with red dots.

Are there any additional operations except installing/enabling the plugin?

Screenshot: http://imgur.com/lWg4sJD

**Comment by naota** [comment]
Enabling the plugin should make it work.

I tried with your text (but Japanese only) on my Atom1.15.0, and I got no red dots.

- Could you try with this text? https://github.com/naota/linter-spell-cjk/blob/master/test-spell.txt
- Could you post your text to gist, to make sure we have the same text?
- What is suggested as correction by the linter?

**Comment by arshcaria** [comment]
Thanks for your reply.

1. I tried the text you gave, but no luck. [http://imgur.com/a/Pcgng](http://imgur.com/a/Pcgng)
2. Kindly refer to [this gist](https://gist.github.com/arshcaria/01b770ecd64ef69472c98fab636d184f) for CJK chars.
3. Atom does not give corrections for CJK chars. [http://imgur.com/a/cZdCU](http://imgur.com/a/cZdCU)

These are tested with a clean Atom installation with no customization but only `linter-spell-cjk` installed.
http://imgur.com/a/39HC7 

Thank you.

**Comment by naota** [comment]
hm, the output seems strange. With spell check by linter-spell, you should see "yellow circle" on correcting line head like this: http://imgur.com/a/76kWN

I guess, you disable linter-spell package and enabled spell-check package? With spell-check package, I get the same result as yours.

**Comment by naota** [comment]
ah, I thought Atom automatically handle package dependencies by just writing it on `package.json`. I just realized it's not...

You need [linter-spell](https://atom.io/packages/linter-spell) to make this package work. (actually, this is linter-spell plugin, so it's no use to have this package alone)

I'll update the code so that it install `linter-spell` by itself.

**Comment by arshcaria** [comment]
Eh, I didn't install `linter-spell`. After installing it and a Windows port of `hunspell`, everything works fine now. Thank you very much. I didn't even know anything about `linter` and `linter-spell` before, OTL...

**Comment by arshcaria** [comment]
btw, the`linter-spell` itself (without 'linter-spell-cjk') ignore Chinese (Kanji) chars. But Kana and Korean ones are treated as spell errors.

**Comment by naota** [comment]
well, it's becuase of hunspell implementation. I don't know why :)
